version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: meta_citizen_postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres_data:
    name: meta_citizen_postgres_data